services:
  server:
    build:
      context: .
      target: dev
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/.config/gcloud/application_default_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=catat-arey
    ports:
      - 8080:8080
