services:
  server:
    build:
      context: .
      target: dev
    secrets:
      - gcloud_credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcloud_credentials
      - GOOGLE_CLOUD_PROJECT=catat-arey
    ports:
      - 8080:8080

secrets:
  gcloud_credentials:
    file: ~/.config/gcloud/application_default_credentials.json